// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/food/addMenu": {
            "post": {
                "tags": [
                    "menu module"
                ],
                "summary": "新增/修改菜單",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳ID",
                        "name": "restaurant_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Food ID",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/index": {
            "get": {
                "tags": [
                    "首頁"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/menu/deleteFood": {
            "delete": {
                "tags": [
                    "menu module"
                ],
                "summary": "刪除食物",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "食物名稱",
                        "name": "food_name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/order/addOrder": {
            "post": {
                "tags": [
                    "order module"
                ],
                "summary": "新增訂單",
                "parameters": [
                    {
                        "description": "訂單資料",
                        "name": "order",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "order_list": {
                                    "type": "object",
                                    "additionalProperties": {
                                        "type": "integer"
                                    }
                                },
                                "restaurant_id": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/order/endOrder": {
            "post": {
                "tags": [
                    "order module"
                ],
                "summary": "結束訂單",
                "parameters": [
                    {
                        "description": "訂單ID",
                        "name": "order",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "order_id": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/order/getOrder": {
            "get": {
                "tags": [
                    "order module"
                ],
                "summary": "取得訂單",
                "responses": {
                    "200": {
                        "description": "code\", \"message\", \"data []Order\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rate/addRate": {
            "post": {
                "tags": [
                    "rates module"
                ],
                "summary": "評價添加/修改",
                "parameters": [
                    {
                        "description": "評價資料",
                        "name": "rate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "comment": {
                                    "type": "string"
                                },
                                "rate": {
                                    "type": "number"
                                },
                                "restaurant_id": {
                                    "type": "string"
                                },
                                "token": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/rate/deleteRate": {
            "delete": {
                "tags": [
                    "rates module"
                ],
                "summary": "刪除評價",
                "parameters": [
                    {
                        "description": "評價ID",
                        "name": "rate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "rate_id": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/addFavoriteRestaurant": {
            "post": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "新增最愛餐廳",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳ID",
                        "name": "restaurant_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/addRestaurant": {
            "post": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "新增餐廳",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳ID",
                        "name": "restaurant_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳名稱",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "營業時間",
                        "name": "business_hours",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "地址",
                        "name": "address",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "電話",
                        "name": "phone",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/deleteRestaurant": {
            "delete": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "刪除餐廳",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳ID",
                        "name": "restaurant_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/findFavoriteRestaurantList": {
            "get": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "查詢最愛餐廳列表",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\", \"data []Restaurant\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/findRestaurantByID": {
            "get": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "透過ID查詢餐廳",
                "parameters": [
                    {
                        "type": "string",
                        "description": "餐廳ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\", \"data Restaurant\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/findRestaurantList": {
            "get": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "查詢餐廳列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "餐廳名稱",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\", \"data []Restaurant\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/findRestaurantRating": {
            "get": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "查詢餐廳評分",
                "parameters": [
                    {
                        "type": "string",
                        "description": "餐廳ID",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\", \"data float64\", \"data rate\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/removeFavoriteRestaurant": {
            "delete": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "刪除最愛餐廳",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳ID",
                        "name": "restaurant_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/restaurant/updateRestaurantInfomation": {
            "post": {
                "tags": [
                    "restaurant module"
                ],
                "summary": "修改餐廳資訊",
                "parameters": [
                    {
                        "description": "token",
                        "name": "token",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳ID",
                        "name": "restaurant_id",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "餐廳名稱",
                        "name": "name",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "營業時間",
                        "name": "business_hours",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "地址",
                        "name": "address",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "電話",
                        "name": "phone",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/forget": {
            "post": {
                "tags": [
                    "user module"
                ],
                "summary": "忘記密碼",
                "parameters": [
                    {
                        "type": "string",
                        "description": "email信箱",
                        "name": "email",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "tags": [
                    "user module"
                ],
                "summary": "獲取用戶信息",
                "responses": {
                    "200": {
                        "description": "code\", \"message\", \"user\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "tags": [
                    "user module"
                ],
                "summary": "登入帳號",
                "parameters": [
                    {
                        "description": "用戶登入資料",
                        "name": "user",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\", \"token\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "tags": [
                    "user module"
                ],
                "summary": "註冊新用戶",
                "parameters": [
                    {
                        "description": "用戶登入資料",
                        "name": "user",
                        "in": "body",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "email": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "password": {
                                    "type": "string"
                                },
                                "phone": {
                                    "type": "string"
                                },
                                "roles": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/verify": {
            "post": {
                "tags": [
                    "user module"
                ],
                "summary": "驗證帳號",
                "parameters": [
                    {
                        "type": "string",
                        "description": "token",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\", \"message\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
